module.exports = {
    "extends": require.resolve("./index"),
    "rules": {
        // Rules that were warnings.
        // TODO: Turn these rules to errors or move them to overrides.
        "array-callback-return": 0,
        "camelcase": 0,
        "consistent-return": 0,
        "default-case": 0,
        "eqeqeq": 0,
        "function-paren-newline": 0,
        "func-names": 0,
        "global-require": 0,
        "guard-for-in": 0,
        "import/newline-after-import": 0,
        "max-len": 0, // TODO: Consider changing to [2, 140],
        "no-empty": 0,
        "no-console": 0,
        "no-mixed-operators": 0,
        "no-multi-assign": 0,
        "no-param-reassign": 0,
        "no-prototype-builtins": 0,
        "no-restricted-syntax": 0,
        "no-return-assign": 0,
        "no-shadow": 0,
        "no-unused-expressions": 0,
        "no-unused-vars": 0,
        "no-useless-escape": 0,
        "no-var": 0,
        "object-shorthand": 0, // TODO: Consider changing to [2, "consistent-as-needed"],
        "one-var": 0,
        "operator-linebreak": 0, // TODO: Consider changing to [2, "after", {"overrides": {"=": "none"}}]
        "prefer-const": 0,
        "prefer-destructuring": 0,
        "prefer-rest-params": 0,
        "prefer-spread": 0,
        "vars-on-top": 0,
        "wrap-iife": 0,

        // Errors
        "array-bracket-spacing": 2,
        "arrow-body-style": 2,
        "arrow-parens": [2, "always"],
        "block-scoped-var": 2,
        "block-spacing": 2,
        "brace-style": 2,
        "comma-spacing": 2,
        "curly": 2,
        "dot-location": 2,
        "dot-notation": 2,
        "indent": [2, 2, {"SwitchCase": 2}],
        "key-spacing": 2,
        "keyword-spacing": 2,
        "newline-per-chained-call": 2,
        "no-buffer-constructor": 2,
        "no-confusing-arrow": 2,
        "no-else-return": 2,
        "no-extra-boolean-cast": 2,
        "no-lonely-if": 2,
        "no-loop-func": 2,
        "no-multi-spaces": 2,
        "no-multiple-empty-lines": 2,
        "no-path-concat": 2,
        "no-trailing-spaces": 2,
        "no-unneeded-ternary": 2,
        "no-useless-concat": 2,
        "no-useless-return": 2,
        "object-curly-newline": [2, {
            "ObjectExpression": {"consistent": true, "multiline": true},
            "ObjectPattern": {"consistent": true, "multiline": true}
        }],
        "object-curly-spacing": 2,
        "object-property-newline": 2,
        "one-var-declaration-per-line": 2,
        "operator-assignment": 2,
        "padded-blocks": 2,
        "prefer-arrow-callback": 2,
        "prefer-promise-reject-errors": 2,
        "prefer-template": 2,
        "quote-props": 2,
        "quotes": 2,
        "semi": 2,
        "semi-spacing": 2,
        "space-before-blocks": 2,
        "space-before-function-paren": 2,
        "space-in-parens": 2,
        "space-infix-ops": 2,
        "space-unary-ops": 2,
        "spaced-comment": 2,
        "yoda": 2
    }
};
